version: "3.8"

services:
  python-app:
    container_name: python-app
    build: 
      context: python-app
    volumes: 
      - app-logs:/logs/

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    expose: 
      - 3100

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes: 
      - /var/log:/data/var/log
      - ./promtail/config.yaml:/etc/promtail/config.yml
      - app-logs:/logs

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes: 
      - grafana:/var/lib/grafana

volumes: 
  grafana:
  app-logs:
