version: "3.8"

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes: 
      - /var/log:/data/var/log
      - ./promtail/config.yaml:/etc/promtail/config.yml
    ports:
      - 9080:9080

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes: 
      - grafana:/var/lib/grafana

volumes: 
  grafana:
