server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /data/var/log/*log
  pipeline_stages:
  - json:
      expressions:
        level: record.level.name
        message: text
        timestamp: record.time.timestamp
        stack_trace: stack_trace
  - labels:
      level:
  - template:
      source: new_key
      template: 'level={{ .level }} timestamp={{ .timestamp }} | {{ or .message .stack_trace }}'
  - output:
      source: new_key
